### ISSUE TITLE
[BUG] does not work with "jsx": "react-jsx" in tsconfig.json file

### ISSUE THREAD

**Issue by ArnasAlex** [nadeesha/ts-prune#108]
**Describe the bug**
Having "jsx": "react" in tsconfig.json file works
Having "jsx": "react-jsx" does not work. 

**To Reproduce**
1. Use "jsx": "react-jsx" in tsconfig.json
2. Run ts-prune
3. Shows error (path to tsconfig was replaced): 
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'path\to\tsconfig\folder\null'
    at Object.realpathSync (fs.js:1529:7)
    at ...\AppData\Roaming\npm\node_modules\ts-prune\lib\analyzer.js:193:66
    at Array.forEach (<anonymous>)
    at ...\AppData\Roaming\npm\node_modules\ts-prune\lib\analyzer.js:192:37
    at Array.forEach (<anonymous>)
    at Object.exports.analyze (...\AppData\Roaming\npm\node_modules\ts-prune\lib\analyzer.js:189:30)
    at Object.exports.run (...\AppData\Roaming\npm\node_modules\ts-prune\lib\runner.js:22:16)
    at Object.<anonymous> (...\AppData\Roaming\npm\node_modules\ts-prune\lib\index.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10) {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'path\to\tsconfig\folder\null'
}

**Expected behavior**
Sould run and not throw error.

**Comment by nadeesha** [comment]
That's a bit weird. ts-prune doesn't consult the `jsx` property of the tsconfig.json. I've got this branch which changes this in test, but the tests pass as well: https://github.com/nadeesha/ts-prune/compare/nadeesha/repro-tsconfig-react-jsx?expand=1

Would you be able to do changes to the integration project at `integration/` to reproduce the issue and tag me?

**Comment by OrineliN** [comment]
Hi @nadeesha, I also have an issue with `react-jsx`, but could be a bit different from reported above:
When I use `react-jsx` ts-prune reports unused exports from `.tsx` files for the exports that are actually used in other files.
I was able to reproduce this issue with following changes in `integration/`:
```diff
diff --git a/integration/testproject/src/A.ts b/integration/testproject/src/A.ts
index 92e1b50..d22849b 100644
--- a/integration/testproject/src/A.ts
+++ b/integration/testproject/src/A.ts
@@ -2,7 +2,8 @@ import B, { foo } from "./B";
 import "./D";
 import { foo as foos } from "./C";
 import type { FooType } from "./B";
+import { FooBarType } from "./Component";
 
-type BarType = FooType;
+type BarType = FooType & FooBarType;
 
 console.log(foo, foos, B);
diff --git a/integration/testproject/src/Component.tsx b/integration/testproject/src/Component.tsx
new file mode 100644
index 0000000..4dc9172
--- /dev/null
+++ b/integration/testproject/src/Component.tsx
@@ -0,0 +1,3 @@
+export type FooBarType = {
+  fooBar: number;
+};
diff --git a/integration/testproject/tsconfig.json b/integration/testproject/tsconfig.json
index fbbfcd7..8fb55b0 100644
--- a/integration/testproject/tsconfig.json
+++ b/integration/testproject/tsconfig.json
@@ -1,5 +1,6 @@
 {
   "compilerOptions": {
+    "jsx": "react-jsx",
     "outDir": "./lib", // this is a comment because tsconfig.json can have comments
     "declaration": true,
     "target": "es5",

```

With the provided changes `FooBarType` is reported as unused:
```
5. Diff between outputs 
The output was not the same as the base
---
7d6
< src/Component.tsx:1 - FooBarType
---
```

If you change jsx to `react` in tsconfig, existing tests would pass with:
```
5. Diff between outputs 
Everything seems to be match! 🎉
```

`react-jsx` was introduced in Typescript 4.1: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#jsx-factories, but ts-prune is using `3.9.5` for now. Probably upgrading could solve the issue.

**Comment by nadeesha** [comment]
Thanks @OrineliN. Maybe upgrading is the way to go.

**Comment by Rendez** [comment]
Thanks for opening this issue, I encountered the same problem caused by `react-jsx` and can confirm that upgrading to 4.1 and the latest ts-morph version solves the problem entirely (at least for my project). I solved it with yarn resolutions on my `package.json`:
```
"resolutions": {
    "typescript": "^4.1.5",
    "ts-morph": "^9.1.0"
  },
  ```

Once @nadeesha is able to confirm this as well and cut a new version, resolutions won't be necessary :)

**Comment by Honga1** [comment]
I am also able to confirm this happening. Typescript 4.1.5, ts-prune 0.8.8.
Changing 'react-jsx' to 'react' fixes this.

**Comment by johot** [comment]
Same finding here as @Honga1 and more :) thx!

**Comment by otroboe** [comment]
I have the same issue, but thanks to @Rendez solution, it works good with yarn `resolutions`!

**Comment by hrazmsft** [comment]
Is there a solution if the package is installed globally or run it with `npx`? I can't use `resolutions` in these cases...
