### ISSUE TITLE
[BUG] import('...').Type does not count Type as being used 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nadeesha/ts-prune#114]
**Describe the bug**
It doesn't look like `ts-prune` is factoring in `import()` statements for using types.

**To Reproduce**

With these files:

```ts
// ambient.ts

let box: import("./types").Box = {
  value: "",
};

console.log({ box });
```

```ts
// types.ts

export interface Box {
    alias?: string;
    value: string;
}
```

`ts-prune` will incorrectly flag `Box` as unused.

**Expected behavior**
`Box` should be detected as being used.

**Optional: reference to the test project**
https://github.com/nadeesha/ts-prune/pull/113

**Additional context**
I'd be happy to fix this if you want :)

**Comment by nadeesha** [comment]
Thank you. If you don't mind me asking, why would one use this syntax instead of the `const foo = import("./types").Box` syntax?

**Comment by JoshuaKGoldberg** [comment]
Great question! I have a few projects with files like `ambient.d.ts` that intentionally are _not_ themselves modules. Per https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types:

> Modules can import types declared in other modules. But non-module global scripts cannot access types declared in modules. Enter `import` types.

There is a `declare global` syntax but for those who are not using it the file for whatever reason, such as to have multiple ambient non-module files, these import types are an alternative.

**Comment by JoshuaKGoldberg** [comment]
Great question! I have a few projects with files like `ambient.d.ts` that intentionally are _not_ themselves modules. Per https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types:

> Modules can import types declared in other modules. But non-module global scripts cannot access types declared in modules. Enter `import` types.

There is a `declare global` syntax but for those who are not using it in the ambient file for whatever reason, such as to have multiple ambient non-module files, these import types are an alternative.

**Comment by JoshuaKGoldberg** [comment]
😢 .

@nadeesha could we reopen this please? It's still an issue.
