### ISSUE TITLE
Processes and reports false positives for non-project files

### ISSUE THREAD

**Issue by emlai** [nadeesha/ts-prune#12]
Thanks for creating ts-prune, it works really well! It just correctly found 80 unused exports from our project!

One problem that I have though is ts-prune processes some files that are not specified in tsconfig.json's "include" property, and also reports false positives for those files.

The exports (not unused) that are reported incorrectly are in the path `.circleci/ecs-deployment/src/aws.ts` and they're imported from `.circleci/ecs-deployment/src/index.ts`, in case these file paths are somehow causing the bug.

<details>
<summary>My tsconfig.json</summary>

```json
{
  "compilerOptions": {
    "allowJs": false,
    "jsx": "react",
    "moduleResolution": "node",
    "outDir": "out",
    "sourceMap": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true,
    "target": "es6",
    "module": "commonjs",
    "lib": [
      "dom",
      "es2017"
    ]
  },
  "include": [
    "backend",
    "client",
    "common",
    "migrations",
    "scripts",
    "test",
    "types"
  ]
}
```

</details>

**Comment by nadeesha** [comment]
Thanks for reporting this @emlai.

If it's not specified in the tsconfig.json, and if you still want to ignore them, what you outlined in #13 seems like a good option.

I'm putting most of my effort right now in performance improvements. It would be a while before I get to this. However, if you want to do a PR for it, I'm more than happy to guide you through it.

In the meantime, `ts-prune | grep -v .circleci/ecs-deployment/src` might work for that directory?

**Comment by emlai** [comment]
Thanks, I ended up adding the following npm script for the time being:

```json
"lint-unused-exports": "ts-prune | (! grep -v .circleci)"
```

This also outputs the correct exit status so we can use it as a lint check in our CI pipeline.

I probably won't have time to look into creating a PR for this... but the performance improvements are definitely welcome. 👍

**Comment by emlai** [comment]
@nadeesha Why was this closed? I test with the latest version (0.2.3) and this still happens.

**Comment by nadeesha** [comment]
@emlai 

> One problem that I have though is ts-prune processes some files that are not specified in tsconfig.json's "include" property, and also reports false positives for those files.

`ts-prune` is designed to only consult files that are defined in your tsconfig.json. It seems like your `.circleci` files are somehow getting dragged into the build. This could be because:
1. A file included is referencing the files inside `.circleci`.
2. An error exists in the Typescript APIs which bypasses `tsconfig.json > include`.

Would appreciate if you can confirm if `1.` is not happening. In that case, there may be an investigation necessary to rule out Typescript as the culprit.

**Comment by emlai** [comment]
@nadeesha Yeah I can confirm `1` is what's happening. A file inside `.circleci` is being imported from one of the project files. The directory structure looks like this (so e.g. we have a separate tsconfig there):

<img width="221" alt="Screen Shot 2019-08-05 at 10 36 08" src="https://user-images.githubusercontent.com/7543552/62447028-0aadee80-b76d-11e9-8ea7-027fa74ddc49.png">

If I add `.circleci/ecs-deployment` to the main tsconfig, then the false positives go away. Adding only `.circleci` doesn't work.

Still, would be nice if there were no false positives reported when we import files not specified in tsconfig.
