### ISSUE TITLE
[Feature Request] Support const object exports

### ISSUE THREAD

**Issue by tony-scio** [nadeesha/ts-prune#123]
In my codebase we have a lot of exports that are const objects that we'd like to prune. Is it at all feasible to support this (perhaps optionally)? If so, I'd be willing to take a stab at a PR given some guidance.

*Example:*
```ts
const obj = {
  foo: 1,
  bar: 2
} as const

export default obj
```

I'd like to know that `foo` is used and `bar` is not.

p.s. I realize that this could be solved by using the below instead, but sometimes we use the above when it's helpful to enforce that all the exported fields have the same type (e.g. exported "stylesheets" of type `{ readonly [id: string]: Readonly<React.CSSProperties> }`).

```ts
export const foo = 1
export const bar = 2
```

p.p.s. Thanks for the excellent library, `ts-prune` overall has been gamechanging for us!

**Comment by nadeesha** [comment]
Thanks for the report. 

Unfortunately, this won't be possible with the current implementation. It's because for all intents and purposes, `obj` (which houses foo and bar) is in fact a used symbol.
