### ISSUE TITLE
[Feature Request] Multiline ignore

### ISSUE THREAD

**Issue by jwoo0122** [nadeesha/ts-prune#127]
From now we should ignore line-by-line.
```js
// ts-prune-ignore-next
export const uncatched = x
// ts-prune-ignore-next
export const anotherUncatched = y
```
It would be very helpful if I can ignore multiple export with single 'ignore' comment(like eslint). 
```js
// ts-prune-disable
export const uncatched = x
export const anotherUncatched = y
// ts-prune-enable
```
This is useful in export-only file, for example entry file for bundling. If I exclude the index file (in tsconfig) then all the reference to module is ignored, which is not expected.

```js
// ts-prune-disable
export { default as Something } from './Something'
export { default as Anotherthing } from './Anotherthing'
export { default as Theotherthing } from './Theotherthing'
// ts-prune-enable
```
Of course we can use `grep -v index.js`. But pipeline throw away `stderr`. `stderr` is more helpful in context of automated build for cancel the process. What I want eventually is like this.
```shell
npm run ts-prune && npm run build && npm run publish
```

**Comment by jwoo0122** [comment]
Maybe this is bug. Single line ignore doesn't work on wildcard export.
```js
// ts-prune-ignore-next
export * from './Something'
```

**Comment by jwoo0122** [comment]
I just found #14 and `tsconfig.files` solved my problem. But still multiline ignore is useful in some case maybe.

**Comment by nadeesha** [comment]
@jwoo0122 I'm going to close this since you found a workaround. Thanks for reporting it.
