### ISSUE TITLE
Better way to ignore false positives

### ISSUE THREAD

**Issue by emlai** [nadeesha/ts-prune#13]
We want to use ts-prune as a part of our lint check. Currently ts-prune reports some false positives (see #12) which we want to ignore. The readme suggests using `ts-prune | grep -v ignoredExport` but this isn't convenient since we have quite many false positives that we need to ignore. My suggestion is to support a special comment like `// ts-prune-ignore` that we can use to mark the identifiers directly in the code.

**Comment by nadeesha** [comment]
I'm going to track this in #12 if you don't mind. Closing.
