### ISSUE TITLE
[Question] also find dead code only used in tests

### ISSUE THREAD

**Issue by sauntimo** [nadeesha/ts-prune#136]
Firstly, this is a really helpful tool, and I have enjoyed hacking dead code out of my projects, so thank you very much for your work on this!

I was wondering if it would be possible to pass a pattern for files which "don't count" in determining whether code is dead.

Say I have some method `foo = () => void` which used to serve some kind of purpose, but is no longer needed. If I import `foo` in to `foo.test.ts` then `foo` is not officially "dead" despite it not serving any purpose in my code base.

It would be awesome if I could pass a pattern like ".test.ts" which would ignore imports in matching files when determining whether code is dead.

I'd love to hear if anyone knows of a way of doing this? or would there be any interest in a PR along these lines?

**Comment by nadeesha** [comment]
That's a really good suggestion. 

If we want to introduce a new feature for this, we might need to introduce a new flag (ex: `--ignore-files=*.test.ts?`) and filter those files out when the source files are imported: https://github.com/nadeesha/ts-prune/blob/5460fce5d1f9fc031559db8ea8bf2f06ed32b0bd/src/analyzer.ts#L236

Or a quicker fix for you might be to create an alternative `tsconfig.json` file (like `tsconfig.ts-prune.json`) and exclude the `test.ts` files from it.

**Comment by sauntimo** [comment]
thanks for this - I'll see if I can find some time to put in a PR 👍
