### ISSUE TITLE
Treat lib exports as used

### ISSUE THREAD

**Issue by nstepien** [nadeesha/ts-prune#14]
Example:

`tsconfig.json`:
```json
{
  "files": [
    "src/index.ts"
  ]
}
```
`src/index.ts`:
```ts
export * from './example';
export const text = 'test';
```
`src/example.ts`:
```ts
export const value = 'test';
```
ts-prune:
```sh
> npx ts-prune
npx: installed 158 in 9.135s
value @ .../src/example.ts:1
text @ .../src/index.ts:2
```

These exports shouldn't be reported as unused, as they're exported/exposed in the entry file.

The tool works great otherwise 👍

**Comment by nadeesha** [comment]
Thanks for reporting this Nicolas. Indeed this is a point of improvement.
