### ISSUE TITLE
[BUG] Incorrect line number on "export * from ..."

### ISSUE THREAD

**Issue by jtbandes** [nadeesha/ts-prune#141]
**Describe the bug**
An incorrect line number is reported by ts-prune when an export is using `export * from ...`:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/14237/128918942-a78bba29-adfe-45b5-8b79-73323b2a4f27.png">

**To Reproduce**
- Clone https://github.com/foxglove/studio/commit/e584cda2853dbd036b7d0109a9fec00fcec867d0
- Run `yarn && yarn lint:unused-exports`

**Expected behavior**
Line 27 is reported (The [`export * from "./useConfig";`](https://github.com/foxglove/studio/blob/e584cda2853dbd036b7d0109a9fec00fcec867d0/packages/studio-base/src/PanelAPI/index.ts#L27) line)

Actual: Line 19 is reported (the line of the [original export definition](https://github.com/foxglove/studio/blob/e584cda2853dbd036b7d0109a9fec00fcec867d0/packages/studio-base/src/PanelAPI/useConfig.ts#L19) in a different file)

**Optional: reference to the test project**
https://github.com/nadeesha/ts-prune/compare/master...jtbandes:export-from

**Comment by jtbandes** [comment]
I think this issue is still valid

**Comment by jtbandes** [comment]
🙃

**Comment by jtbandes** [comment]
This issue is still valid.

**Comment by nadeesha** [comment]
@jtbandes Will happily accept a PR for this.

**Comment by jtbandes** [comment]
I've investigated this a little but I'm lost on how to make the correct fix. It seems like the return value from `file.getExportSymbols()` is already 'wrong' (it contains information about the original symbols being exported, skipping over the `export *`). Should we be using `file.getExportDeclarations()` instead? (But I'm not sure how to correctly go from an export declaration to a list of exported symbols)

**Comment by nadeesha** [comment]
I'm in favor of changing it to `getExportDeclarations`, if you think that'd yield the correct line numbers. Unfortunately, we can only be as correct as the exposed AST via `ts-morph`.
