### ISSUE TITLE
[BUG] does not understand `import('./specifier').Type` references

### ISSUE THREAD

**Issue by cspotcode** [nadeesha/ts-prune#166]
**Describe the bug**

When something is exported from `foo.ts` and referenced from another via `import('./foo').Type` type syntax, ts-prune thinks it is unused.

**To Reproduce**

Create a project with two files, `type.ts` with `export type Type = number;` and `index.ts` with `const a: import('./type').Type = 0;`

Run ts-prune.  It lists `Type` as being unused.

<details><summary>Full code sample</summary>
```
// tsconfig.json
{}
```

```
// index.ts
const foo: import('./other').Type = 1;
```

```
// other.ts
export type Type = number;
```

Output
```
❯ ./node_modules/.bin/ts-prune
other.ts:2 - Type

```
</details>

**Expected behavior**

When something is referenced via an inline `import()` type reference, ts-prune should understand it is being used.

**Optional: reference to the test project**

https://github.com/cspotcode/ts-prune/tree/patch-1

**Additional context**

This problem is very common in projects using allowJs because there's no good `import type` syntax in uncompiled plain JS files, so you end up with a lot of this sort of JSDoc:

```
/**
 * @param {import('./other/file').Options} options
 * @return {import('./other/service').Service}
 */
function (options) {
```

Seems related to https://github.com/nadeesha/ts-prune/issues/2#issuecomment-505027710 and https://github.com/nadeesha/ts-prune/issues/29

**Comment by nadeesha** [comment]
This is a valid bug. Acknowledged. Will happily accept a PR for this.
