### ISSUE TITLE
Feature request: flag unused non-exports, such as functions which are never invoked

### ISSUE THREAD

**Issue by cspotcode** [nadeesha/ts-prune#167]
My team has some very big files in our codebase, so I'm guessing we have some non-exported functions that are completely unused.  ts-prune does not seem to flag these functions.

The feature request is to specifically flag function declaration statements that are not referenced anywhere else.

```
function isNotExportedAndNeverReferenced() {/* should be flagged by ts-prune */}
```

I suppose this could also be extended to `const a = function()...` and `var a = function()...`

**Comment by cspotcode** [comment]
Someone pointed out that this is handled by `noUnusedLocals`.  I now realize this feature request doesn't make a ton of sense.  I suppose in a perfect world it would still be nice for one tool to flag all unused code, both exports and locals, but probably not worth the implementation effort.

**Comment by nadeesha** [comment]
Thanks for raising the issue and documenting the workaround. Will close this for now.
