### ISSUE TITLE
[FEATURE] Include git blame info of who/when last owned the unused line

### ISSUE THREAD

**Issue by michaeldrotar** [nadeesha/ts-prune#171]
Not sure if you're taking feature requests but figured I'd ask.

We have a rather large team and thousands of unused exports at this point that I've been making my way through. If I put up a PR of 500 lines we could remove, I'd like to have the PR reviewed by the person that added those lines (and group PRs by who added what). Currently figuring that out is a very manual process - if the output included their name then I could `| grep NAME` and do batches by person.

The `git blame` data would also include a date so I could `| grep 2021-` to find things from last year or `| grep 2022-01` to find things months old -- which would also be helpful since we sometimes add code that we plan to use in the next PR in order to have smaller PRs for review.

**Describe the implementation**
```
Configuration options
-b --blame - append the author and date from git blame
```
or
```
Configuration options
-a --author - include the author that last touched the unused line
-t --timestamp - include the timestamp that the line was last touched
```

**Sample output**
```
packages/foo/src/components/Foo.tsx:11 (John Doe on 2021-02-18 10:25:53 -0500) - FooItem
packages/foo/src/components/Bar.tsx:4 (Jane Doe  on 2020-01-03 22:43:03 -0500) - BarWrapper
```

**Additional Thoughts**
This could be expanded to make filters on name/date, like only show things that are 3 months old would be useful.

**Comment by nadeesha** [comment]
I'd love to extend `ts-prune`, but I feel like I asked more from the Typescript source tree than I could have.

I agree that this is a valid and a valuable feature.

Would you instead be able to use some bash magic here? ts-prune already gives you the file and the line number, and it should be easy enough (?) to run a git blame on that externally to ts-prune.

**Comment by michaeldrotar** [comment]
I was initially considering a node script to do just that yeah - and then I thought about needing to use child_process and my inner child died a little and it seemed generally handy so thought I'd ask first :) 

But yes certainly doable haha

**Comment by rubengmurray** [comment]
If you make the bash script @michaeldrotar, let us know.. sounds cool 👍

**Comment by nadeesha** [comment]
I think you can use `git log -L` and pass in the output from ts-prune to that. Closing this issue. Please reopen if need be.
