### ISSUE TITLE
[BUG] Windows path separators should be printed as Unix path separators

### ISSUE THREAD

**Issue by Zamiell** [nadeesha/ts-prune#179]
On Windows, I can use the following command to ignore the "index.ts" file:

```
npx ts-prune --error --ignore 'src\index.ts'
```

If instead, I specify it with a forward slash like this:

```
npx ts-prune --error --ignore 'src/index.ts'
```

Then it won't work at all. I think that this is a bug, because forward slashes should work seamlessly, like they do for any other command line tool (ESLint, Prettier, etc.).

However, the problem is even worse, because when I run `ts-prune` in CI with my backwards slashes, now the ignore directive won't work at all, because it is looking for Windows-style paths instead of Linux-style paths. So it becomes impossible to have the linter pass both locally and in CI.

Thus, I think `ts-prune` should work in the same way as ESLint, Prettier, and other linters - it should always print out paths in Linux-style, and always accept paths in Linux-style.

**Comment by nadeesha** [comment]
Thanks. This seems like a bug. I'll accept a PR for it.

**Comment by Zamiell** [comment]
@nadeesha Can you take a look at the PR?
