### ISSUE TITLE
[BUG] Does not install CLI on windows, ts-prune is not a command

### ISSUE THREAD

**Issue by douglasg14b** [nadeesha/ts-prune#188]
**Describe the bug**
After installing via yarn, and restarting my terminal, `ts-prune` is not a command.

![image](https://user-images.githubusercontent.com/1400380/176786837-5fd607da-d685-4450-88fe-f59469ac1a11.png)

**To Reproduce**
1. Install  on widnows
2. Try and run `ts-prune` in your project

**Expected behavior**
The CLI is accessable

**Additional context**

**Comment by douglasg14b** [comment]
I'm following the install commands in the readme, which do not install globally.

ie:

```
yarn add -D ts-prune
```

**Comment by codymurphyjones** [comment]
It doesn't tell you that you will be able to use it locally, thats all dependent on your personal computers configuration.

You can still use it within npm scripts perfectly fine if its in the node_modules

or npx ts-prune

There are far too many different personal preferences to discuss every installation usecase, so they cover the most common one and assume you know enough about your environment to put the pieces together.

**Comment by douglasg14b** [comment]
> It doesn't tell you that you will be able to use it locally, thats all dependent on your personal computers configuration.

What configuration, specifically, affects this?

**Comment by codymurphyjones** [comment]
Your operating systems path configuration is typically what determines that can be ran directly inside of your terminal without a script.

This specific library is not claiming or attempt to offer what you're asking for, this library is intended to be used locally alongside a yarn or npm script to run `ts-prune`.  However you would still be able to achieve what you are asking for with `npm install ts-prune -g`
