### ISSUE TITLE
[BUG] Cross-platform issue with ignore paths

### ISSUE THREAD

**Issue by romanc** [nadeesha/ts-prune#203]
**Describe the bug**

I am having trouble to configure `ts-prune` in a cross-platform environment. It seems that files ignored with the `-i` flag are not matched in a cross-platform friendly way, meaning `-i src/file.ts` and  `-i src\\file.ts` will give different results depending on your OS.

**To Reproduce**

1. Configure `ts-prune` to ignore paths that include a folder delimiter (e.g. `/` on unix-like systems or `\\` on windows).
2. Notice how the results are different when you switch the environment

**Expected behavior**

I'd expect ignore paths to work regardless of the environment.

**Comment by jkieboom** [comment]
Ping, still an issue.

**Comment by romanCattaneo** [comment]
@jkieboom Based on [this deprecation note](https://github.com/nadeesha/ts-prune/commit/9138742deb0cdf9b9844dffa8421ab265c3d8f44), I wouldn't expect anything moving here unless we fork and fix it ourselves. Something to discuss ...
