### ISSUE TITLE
[BUG] Satisfies operator

### ISSUE THREAD

**Issue by lucioreyli** [nadeesha/ts-prune#218]
**Describe the bug**
I'm using the new TypeScript operator `satisfies` and the `ts-prune` is reporting as unused in my file.

**To Reproduce**
1. Declare a type as base to a variable and use like this:
```typescript
export type User = Record<string, any>;
const user = {
	email: 'lucioreyli@github.co',
	password: 'happy-new-year-23'
} satisfies User;
```

```typescript
export type CreateCompanyDTO = { name: string };

type CreateCompanySchema = Record<keyof CreateCompany, any>;
/// CreateCompanySchema -> { name: any };

export const createCompanySchema = {
  name: z.string(),
} satisfies CreateCompanySchema;

// yarn ts-prune --error
// satisfies
// CreateCompanySchema (used in module)
```

**Expected behavior**
No warnings about the `satisfies` usage.

**Comment by jtbandes** [comment]
I'm having the same issue.

**Comment by jtbandes** [comment]
Thanks for the tip.

It does seem like this issue could be resolved by just upgrading the `ts-morph` dependency, but I'm not sure if that will happen as this project is now just in maintenance mode.

**Comment by JustFly1984** [comment]
+1

**Comment by jtbandes** [comment]
Stale issue rebuttal 😄

**Comment by chriskuech** [comment]
Interesting how this
* does not apply to all cases of `satisfies`
* sometimes flags `satisfies`
* sometimes flags the type applied by `satisfies`

**Comment by nadeesha** [comment]
Thanks for the submission. Unfortunately, ts-morph  upgrading is a tall ask. We had problems the last time someone contributed this upgrade.
