### ISSUE TITLE
New false positives in latest release (0.1.3) when using `import * as x`

### ISSUE THREAD

**Issue by emlai** [nadeesha/ts-prune#22]
Exports imported using `import * as x` and used as `x.foo` are being reported incorrectly as unused in the 0.1.3 and 0.1.1 releases. Previously, with 0.0.7, these weren't reported as unused.

**Comment by nadeesha** [comment]
Thanks. This is one of the tradeoffs that I've had to make with the latest perf improvements. Feel free to send a PR if you can dig into it or if you can add some lines to the README.

**Comment by emlai** [comment]
Ok, good to know. I decided to stay on the older version for now since with the new version we got 368 new reports. Many of them seemed to be valid issues, but also a lot of them were about these `* as x` imports, and it would be too much work to go through all of them manually (also one of the reasons for requesting #23).

**Comment by nadeesha** [comment]
This is now fixed in `v0.2.0` with #25.

Thanks for the report @emlai.
