### ISSUE TITLE
[BUG] `-u` not working

### ISSUE THREAD

**Issue by MoSattler** [nadeesha/ts-prune#222]
If I use the tool with the `-u` flag, like this:
```
npx ts-prune -u
```

I still get results which have this text and are in fact used:
```
(used in module)
```

**Comment by Zhhanou** [comment]
I have the same problem.

**Comment by Zhhanou** [comment]
The reason is that the author did not publish NPM package. The latest NPM package version 0.10.3 still does not include this feature '--unusedInModule'.

**Comment by m0un10** [comment]
Until it's published.... here is a workaround...

`ts-prune | grep -v 'used in module'`

**Comment by eddie-dunn** [comment]
If you want to replicate `ts-prune -u -e` (e.g., if you need it in CI) you'll have to do

```
set -o pipefail; ts-prune -e | grep -v 'used in module'
```
