### ISSUE TITLE
False positives for unexported interfaces in .d.ts files

### ISSUE THREAD

**Issue by emlai** [nadeesha/ts-prune#39]
When I have unexported interfaces in a .d.ts file and only use them inside that file (e.g. as a property type in another interface), ts-prune reports them in its output.

**Comment by nadeesha** [comment]
I need to dig deeper into why this happens. As a workaround, maybe you can ignore `.d.ts` files as outlined by the README? Thanks as always for reporting this.

**Comment by emlai** [comment]
@nadeesha Yeah, I ended up ignored that specific .d.ts file. However all other .d.ts files work fine.

**Comment by nadeesha** [comment]
I'm not sure I've enough information to reproduce this. Please re-open if this is a recurring issue. Thanks.

**Comment by emlai** [comment]
Just tested with v0.3.0 and it still happens.
