### ISSUE TITLE
add comments // ts-prune-disable-next-line

### ISSUE THREAD

**Issue by JustFly1984** [nadeesha/ts-prune#42]
the same way to mark false positives.

For example I'm using Gatsby.js and React.js with typescript, and we use 'ts-loader', 'source-map-support', 'ts-node' to import ts files in js files, so ts-prune do not parse js files, hence false negatives. 

If you implement `--fix` option, without adding disabling commits, it could potentially remove correct exports

**Comment by nadeesha** [comment]
Implementing an ignore comment is a good suggestion.

I'm wary of implementing a `--fix` option because I'm not sure we're covering all our bases in reporting false positives.

**Comment by getsaf** [comment]
My solution for this was to create a file named `unusedImportsWhitelist.ts` and simply import the things I wish to whitelist:

```typescript
import './src/foo';
// -- or --
import { specificThing } from './src/bar';
```
