### ISSUE TITLE
Still false positives on "barrel export" index files

### ISSUE THREAD

**Issue by yegrushka** [nadeesha/ts-prune#46]
**Steps to reproduce**
1. git clone https://github.com/yegrushka/ts-prune.git
2. git checkout fix/barrel-export
3. ./integration/test.sh

**Expected**
Tests not to fail
**Actual**
Tests are failing

**Additional info**
Issue #40 is closed by PR #41, but the issue still exists.
If you use named export syntax to re-export a type, ts-prune works great.
But if you use * wildcard, it still reports with a false positive on this import.
I have created a reproducible example in my fork.

**Comment by nadeesha** [comment]
Thanks for reporting this @yegrushka. This is now fixed via #55.
