### ISSUE TITLE
[BUG] error ts-prune@0.5.0: The engine "node" is incompatible with this module. Expected version "^12.16.3". Got "13.3.0"

### ISSUE THREAD

**Issue by JustFly1984** [nadeesha/ts-prune#58]
**Describe the bug**
Can't install any version newer than 0.3.0 due to package.json node.js version limitation. please relax the rule to support node.js versions above 12.

**To Reproduce**
1. try to install dependency with `yarn add -D ts-prune` in project with node 13

**Expected behavior**
Should support node 13 and 14.

**Additional context**
I have my own opensource npm package, and I did the same mistake to set engines: { node } in package.json, but 13 >= node, which broke yarn install for those who used node 12. removing engines node version completely solved issues for end users.

```sh
yarn add -D ts-prune@0.6.0  
error ts-prune@0.6.0: The engine "node" is incompatible with this module. Expected version "^12.16.3". Got "13.3.0"
```

```sh
yarn add -D ts-prune@0.5.0  
error ts-prune@0.5.0: The engine "node" is incompatible with this module. Expected version "^12.16.3". Got "13.3.0"
```

```sh
yarn add -D ts-prune@0.4.0  
error ts-prune@0.4.0: The engine "node" is incompatible with this module. Expected version "^12.16.3". Got "13.3.0"
```

```sh
yarn add -D ts-prune@0.3.5  
error ts-prune@0.3.5: The engine "node" is incompatible with this module. Expected version "^12.16.3". Got "13.3.0"
```

Thank you for a great tool!

**Comment by nadeesha** [comment]
@JustFly1984 Sorry about this. This was an oversight on my part. Fix is incoming.

**Comment by JustFly1984** [comment]
thank you for fast response!
