### ISSUE TITLE
[BUG] Yarn version requirement is unnecessarily stringent

### ISSUE THREAD

**Issue by pelotom** [nadeesha/ts-prune#62]
Similar to #58, the Yarn version required by this package is unnecessarily stringent:

```
error ts-prune@0.6.3: The engine "yarn" is incompatible with this module. Expected version "^1.22.4". Got "1.18.0"
```

I don't understand why this package should have any opinion about which version of Yarn I use. The reason this is a problem is that there is a bug in the latest version of Yarn which prevents upgrading packages: https://github.com/yarnpkg/yarn/issues/7807 So between that issue and this I'm literally not able to do any upgrades in my project.

**Comment by nadeesha** [comment]
Thanks for reporting @pelotom. I've removed this restriction.

**Comment by pelotom** [comment]
Thanks for the quick response!
