### ISSUE TITLE
[feature request] allow passing multiple tsconfigs

### ISSUE THREAD

**Issue by phiresky** [nadeesha/ts-prune#65]
We have multiple projects (just different tsconfigs, not linked via tsconfig references) that have different files, but they reference each other via yarn workspaces. This means that ts-prune finds lots of false positives for exports that are used from the other project. It would be great if ts-prune could handle reading from multiple tsconfigs and analyze all files together.

**Comment by nadeesha** [comment]
I'm not sure what kind of support I can expect from the dependencies to support multiple tsconfig files. To get around this, is it possible to create one encompassing project on root and feed everything to ts-prune as one project?

**Comment by nadeesha** [comment]
Apologies @phiresky. With the bandwidth I have now, I won't be able to support this feature.

**Comment by phiresky** [comment]
Wanted to mention to others that may encounter this: Creating a tsconfig just for ts-prune that includes all files from multiple projects works as a workaround, even if that causes some conpile errors due to different compile options since ts-prune doesn't care about stuff like noImplicitAny etc

**Comment by nadeesha** [comment]
Thank you. Appreciate you sharing the findings here.

**Comment by qpwo** [comment]
@phiresky How did you include all files? I can think of a few ways to do the tsconfig

1. `"include": ["./**/*.ts"]`
2. `"references": [ { "path": "./pkg1" }, { "path": "./pkg2" }, ...]`
3. `"paths": { "pkg1/*": ["./pkg1/*"], "pkg2/*": ["./pkg2/*"],...}`

Or any chance you have the bandwidth @nadeesha ?

(Some search terms for this issue for future googlers:)

- typescript project references
- monorepo
- multi-package app, multi-package project
- npm workspace
- submodules
