### ISSUE TITLE
[feature request] handle unused parts of import * from 

### ISSUE THREAD

**Issue by phiresky** [nadeesha/ts-prune#70]
Currently, ts-prune marks everything in a file that has a `import * as ns from 'file'` import as definitely used. It would be useful to be more specific here. I think it should be possible by getting all locations with star imports, finding all usages of the `ns` symbol, and matching the list of members accessed on that symbol with the list of exports in the file.

I might make a PR for this later, I'm opening this mostly to be able to discuss it or maybe if there's existing information on this. Would be great if you could let me know if something like this has already been attempted or if I'm missing something.

**Comment by JustFly1984** [comment]
@phiresky would be nice if it could track unused class methods/properties also

**Comment by DriesVS** [comment]
I'm getting false positives with version 0.8.4 with an intermediate index file that exports multiple import all's.

`import * as test1 from "./test1";
import * as test2 from "./test2";


export {
    test1,
    test2
}`

**Comment by DriesVS** [comment]
I'm getting false positives with version 0.8.4 with an intermediate index file that exports multiple import all's.

```import * as test1 from "./test1";
import * as test2 from "./test2";


export {
    test1,
    test2
}```

**Comment by DriesVS** [comment]
I'm getting false positives with version 0.8.4 with an intermediate index file that exports multiple import all's.

```
import * as test1 from "./test1";
import * as test2 from "./test2";


export {
    test1,
    test2
}
```

**Comment by DriesVS** [comment]
I'm getting false positives with version 0.8.4 when an intermediate index file only exports the import.

```
import * as test1 from "./test1";
import * as test2 from "./test2";


export {
    test1,
    test2
}
```
