### ISSUE TITLE
Dismiss warns of default exports in use

### ISSUE THREAD

**Issue by koooge** [nadeesha/ts-prune#76]
**Describe the bug**
Hi There. ts-prune is one of the best tools I wanted!

https://github.com/nadeesha/ts-prune/blob/master/integration/outfile.base

The output includes default export in C.ts in spite of it is used by A.ts. Is this intended? I don't think that would be useful.

https://github.com/nadeesha/ts-prune/blob/master/integration/testproject/src/A.ts

**To Reproduce**
`$ npm test`

**Expected behavior**
Dismiss warns of the default exports in use.

**Comment by nadeesha** [comment]
@koooge I'm not sure if I'm missing anything here, but I can't see the default import of C.ts being used by A.ts.

https://github.com/nadeesha/ts-prune/blob/master/integration/testproject/src/A.ts#L1-L8

It seems to only use the `foo` export?

**Comment by koooge** [comment]
Oh? I misunderstood. Sorry!
