### ISSUE TITLE
[Docs] CI command doc example

### ISSUE THREAD

**Issue by vitalyiegorov** [nadeesha/ts-prune#77]
**Describe the bug**
A `package.json` script example with correct error code for CI usage:
```
"find-deadcode": "ts-prune | (! grep -v -s -E '(index|selector|graphql|mock)\\.ts|\\.(web|native|ios|android)\\.|(migrations|requirements|dist|deprecated)/')"
```
`grep` has 3 conditional groups:
- excluded files
- excluded file name sub-extensions
- excluded folders

General improvement is negative `!` result of grep which returns correct exit code(0) when nothing is returned - which means that this check was successful.

Would be nice to add this to official readme to help everyone.

Thank you for this lib, it helped us significantly by removing unused or unnecessary exported code! @nadeesha

**Comment by nadeesha** [comment]
This is indeed a pretty good suggestion. Thank you. Let me try to take this up later on. If you're interested in creating a PR and contributing, that'd be much appreciated as well.

**Comment by vitalyiegorov** [comment]
@nadeesha Done #79
