### ISSUE TITLE
[BUG] Cannot read property 'getLeadingCommentRanges' of undefined

### ISSUE THREAD

**Issue by ccakes** [nadeesha/ts-prune#83]
**Describe the bug**
https://github.com/nadeesha/ts-prune/blob/5a6c91e37ae957e78d918e711fbb7bdedd37b0e3/src/analyzer.ts#L75-L77

`getDescendantAtPos()` returns null/undefined when run against [Zapatos](https://github.com/jawj/zapatos)-generated code. I modified analyzer.ts like so
```typescript
  const descendant = file.getDescendantAtPos(symbolLinePos);
  if (!descendant) {
    console.log("File:", file.compilerNode.fileName);
    return false;
  }

  const comments = descendant.getLeadingCommentRanges();

  if (!comments) {
    return false;
  }
```
and ran it against my project and the file generating the errors is `src/zapatos/src/index.ts`

**To Reproduce**
```shell
$ git clone https://github.com/jawj/zapatos
$ cd zapatos
$ npx ts-prune
```

**Expected behavior**
No error

**Additional context**
For the record - I'm not affiliated with the Zapatos project at all, those files are just injected when that library is used in other projects and it's causing this error

**Comment by nadeesha** [comment]
Thanks for the report @ccakes
