### ISSUE TITLE
[Improvement] Add Travis-CI for pull request

### ISSUE THREAD

**Issue by vitalyiegorov** [nadeesha/ts-prune#88]
@nadeesha Right now pull requests does not perform [unit tests via CI](https://travis-ci.org) and other automatic checks, would like to introduce this support, also other automatic checks could be added, like https://deepscan.io/dashboard/, https://codecov.io, this will improve overall code quality and simplify merging process.

Another cool feature is an automatic `npm version` publication upon merging this pull requests, reach me and we can set it up also.

What do you think?

**Comment by nadeesha** [comment]
@vitalyiegorov I think this is done already with [github workflows](https://github.com/nadeesha/ts-prune/tree/master/.github/workflows)?

**Comment by vitalyiegorov** [comment]
True, but it is not configured properly for pull requests https://github.com/nadeesha/ts-prune/pull/81/checks, and also other automatic checks could be added,

**Comment by nadeesha** [comment]
Thanks for noticing this. I've fixed this with #90.
