### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by Timmmm** [nadeesha/ts-prune#94]
Unfortunately this doesn't seem to detect Typescript code in `.vue` files out of the box.

To reproduce, create a basic Vue project (Vue CLI can do this), and then export something from a `.ts` file and import it in a `.vue` file. `ts-prune` will report it as unused.

My `tsconfig.json` file does include `.vue` files:

```
  "include": [
    ...
    "src/**/*.vue",
  ],
```

However I guess it doesn't understand Vue single file components. They are converted to Typescript during webpack compilation by the `vue-loader` plugin.

**Comment by nadeesha** [comment]
@Timmmm Does the typescript compiler understand `.vue` files itself? If not, I'm not sure whether we can fix this.

If there's a convention to the `.ts` files that export vue components, you can ignore them via a CLI option.

**Comment by Timmmm** [comment]
Yeah it seems to. I [mostly fixed it in your competitor project just by changing a setting](https://github.com/pzavolinsky/ts-unused-exports/issues/162#issuecomment-703539134) though honestly I'm not really sure how it works. Maybe something to do with `isMixedContent`?

**Comment by nadeesha** [comment]
@Timmmm If you're interested in having this, I'd welcome a PR.

**Comment by Timmmm** [comment]
Easier just to use `ts-unused-exports`, sorry!
