### ISSUE TITLE
Feature request: report unused dependencies in package.json

### ISSUE THREAD

**Issue by danvk** [nadeesha/ts-prune#96]
If a library listed in the `dependencies` section of `package.json` is never `import`ed, then the dependency should be removed. Dependencies like `typescript` or `@types/lodash` should go in `devDependencies`, not `dependencies`.

I have a branch with this working. @nadeesha do you see this sort of analysis as in-scope for ts-prune? It's like an unused export, just from `package.json` rather than your own code.

**Comment by Milancos** [comment]
This is actually a very usefull feature and my company would love to see it. That being said not sure how you see this library in the future and if you want it to do more things

**Comment by nadeesha** [comment]
Sorry about the delay on this one. I've been away for a while. @danvk I'm keen to see your implementation.
