### ISSUE TITLE
[FEATURE] Add support for cucumber-js classes/steps

### ISSUE THREAD

**Issue by vitalyiegorov** [nadeesha/ts-prune#99]
**Describe the bug**
When using a cucumber for e2e, you have to create classes/steps files that are exported but not imported anywhere, this classes are visible to cucumber-js via configuration settings(`directory paths` or extensions `*.steps.ts`) but this files may contain other unneeded exports, would be nice to create a way to ignore errors with such classes and leave checks for other stuff in this files.

**To Reproduce**
1. Create class with `export class MyClass {}`

**Expected behavior**
We see no errors for certain classes

**Comment by nadeesha** [comment]
@vitalyiegorov You can use the ignore pattern documented here to ignore a certain extension via `grep`: https://github.com/nadeesha/ts-prune#how-do-i-ignore-a-specific-path
